Fix container security policy
A default `insecureAcceptAnything` breaks `rpm-ostree update`:

```
$ rpm-ostree update --check
error: Preparing import: Fetching manifest: containers-policy.json
specifies a default of `insecureAcceptAnything`; refusing usage
```

We must reject by default, and explicitly dictate the applicable policy
for each runtime.